[package]
name = "oxygraph"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A graph tool library for building memory efficient and fast graphs"

[dependencies]
oxygraph-derive = { workspace = true, optional = true }
num-traits = "0.2.19"
# Optional dependency for serialization and deserialization of graph data structures
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = ["oxygraph-derive"]
serde = [
	"oxygraph-derive/serde",
	"dep:serde",
] # Enable serialization and deserialization support

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "graph_bench"
harness = false
